/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "/Users/breeze/Desktop/wiki/node_modules/@vuepress/core/lib/client/components/GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-f9c78158",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f9c78158").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-772816dd",
    path: "/tech/Javascript/Node.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-772816dd").then(next)
    },
  },
  {
    name: "v-1ad1eedf",
    path: "/tech/Javascript/Node10.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1ad1eedf").then(next)
    },
  },
  {
    name: "v-617fce67",
    path: "/tech/Javascript/Node2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-617fce67").then(next)
    },
  },
  {
    name: "v-781d6f47",
    path: "/tech/Javascript/Node3.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-781d6f47").then(next)
    },
  },
  {
    name: "v-e289dfb2",
    path: "/tech/Javascript/Node4.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e289dfb2").then(next)
    },
  },
  {
    name: "v-b54e9df2",
    path: "/tech/Javascript/Node5.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b54e9df2").then(next)
    },
  },
  {
    name: "v-88135c32",
    path: "/tech/Javascript/Node6.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-88135c32").then(next)
    },
  },
  {
    name: "v-2d9cd8b2",
    path: "/tech/Javascript/Node8.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2d9cd8b2").then(next)
    },
  },
  {
    name: "v-5ad81a72",
    path: "/tech/Javascript/Node7.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5ad81a72").then(next)
    },
  },
  {
    name: "v-006196f2",
    path: "/tech/Javascript/Node9.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-006196f2").then(next)
    },
  },
  {
    name: "v-00eb47c4",
    path: "/tech/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-00eb47c4").then(next)
    },
  },
  {
    path: "/tech/index.html",
    redirect: "/tech/"
  },
  {
    name: "v-52c65387",
    path: "/tech/react/react.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-52c65387").then(next)
    },
  },
  {
    name: "v-66108fc7",
    path: "/tech/react/react2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-66108fc7").then(next)
    },
  },
  {
    name: "v-bdd30db2",
    path: "/tech/react/react3.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-bdd30db2").then(next)
    },
  },
  {
    name: "v-47c73af2",
    path: "/tech/react/react4.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-47c73af2").then(next)
    },
  },
  {
    name: "v-37b79c4e",
    path: "/tech/react/reactnative.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-37b79c4e").then(next)
    },
  },
  {
    name: "v-1d6f4ceb",
    path: "/tech/vue/vue.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1d6f4ceb").then(next)
    },
  },
  {
    name: "v-7f6c96f2",
    path: "/tech/vue/vue2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7f6c96f2").then(next)
    },
  },
  {
    name: "v-0c302667",
    path: "/tech/vue/vue3.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0c302667").then(next)
    },
  },
  {
    name: "v-cfdf1832",
    path: "/tech/vue/vuepress.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-cfdf1832").then(next)
    },
  },
  {
    name: "v-2e8f2d86",
    path: "/tech/%E5%91%A8%E8%BE%B9%E5%BC%80%E5%8F%91%E6%8A%80%E6%9C%AF/gatsbyjs.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2e8f2d86").then(next)
    },
  },
  {
    path: "/tech/周边开发技术/gatsbyjs.html",
    redirect: "/tech/%E5%91%A8%E8%BE%B9%E5%BC%80%E5%8F%91%E6%8A%80%E6%9C%AF/gatsbyjs.html"
  },
  {
    path: "/tech/周边开发技术/gatsbyjs.html",
    redirect: "/tech/%E5%91%A8%E8%BE%B9%E5%BC%80%E5%8F%91%E6%8A%80%E6%9C%AF/gatsbyjs.html"
  },
  {
    name: "v-0055293e",
    path: "/tech/%E5%91%A8%E8%BE%B9%E5%BC%80%E5%8F%91%E6%8A%80%E6%9C%AF/git.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0055293e").then(next)
    },
  },
  {
    path: "/tech/周边开发技术/git.html",
    redirect: "/tech/%E5%91%A8%E8%BE%B9%E5%BC%80%E5%8F%91%E6%8A%80%E6%9C%AF/git.html"
  },
  {
    path: "/tech/周边开发技术/git.html",
    redirect: "/tech/%E5%91%A8%E8%BE%B9%E5%BC%80%E5%8F%91%E6%8A%80%E6%9C%AF/git.html"
  },
  {
    name: "v-04d1bd87",
    path: "/tech/%E5%91%A8%E8%BE%B9%E5%BC%80%E5%8F%91%E6%8A%80%E6%9C%AF/hexo.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-04d1bd87").then(next)
    },
  },
  {
    path: "/tech/周边开发技术/hexo.html",
    redirect: "/tech/%E5%91%A8%E8%BE%B9%E5%BC%80%E5%8F%91%E6%8A%80%E6%9C%AF/hexo.html"
  },
  {
    path: "/tech/周边开发技术/hexo.html",
    redirect: "/tech/%E5%91%A8%E8%BE%B9%E5%BC%80%E5%8F%91%E6%8A%80%E6%9C%AF/hexo.html"
  },
  {
    name: "v-7f77e00c",
    path: "/tech/%E5%91%A8%E8%BE%B9%E5%BC%80%E5%8F%91%E6%8A%80%E6%9C%AF/%E5%89%8D%E5%90%8E%E7%AB%AF%E5%BC%80%E5%8F%91%E6%A6%82%E8%BF%B0(%E4%B8%89).html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7f77e00c").then(next)
    },
  },
  {
    path: "/tech/周边开发技术/前后端开发概述(三).html",
    redirect: "/tech/%E5%91%A8%E8%BE%B9%E5%BC%80%E5%8F%91%E6%8A%80%E6%9C%AF/%E5%89%8D%E5%90%8E%E7%AB%AF%E5%BC%80%E5%8F%91%E6%A6%82%E8%BF%B0(%E4%B8%89).html"
  },
  {
    path: "/tech/周边开发技术/前后端开发概述(三).html",
    redirect: "/tech/%E5%91%A8%E8%BE%B9%E5%BC%80%E5%8F%91%E6%8A%80%E6%9C%AF/%E5%89%8D%E5%90%8E%E7%AB%AF%E5%BC%80%E5%8F%91%E6%A6%82%E8%BF%B0(%E4%B8%89).html"
  },
  {
    name: "v-150c9530",
    path: "/tech/%E5%91%A8%E8%BE%B9%E5%BC%80%E5%8F%91%E6%8A%80%E6%9C%AF/%E5%89%8D%E5%90%8E%E7%AB%AF%E5%BC%80%E5%8F%91%E6%A6%82%E8%BF%B0(%E4%BA%8C).html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-150c9530").then(next)
    },
  },
  {
    path: "/tech/周边开发技术/前后端开发概述(二).html",
    redirect: "/tech/%E5%91%A8%E8%BE%B9%E5%BC%80%E5%8F%91%E6%8A%80%E6%9C%AF/%E5%89%8D%E5%90%8E%E7%AB%AF%E5%BC%80%E5%8F%91%E6%A6%82%E8%BF%B0(%E4%BA%8C).html"
  },
  {
    path: "/tech/周边开发技术/前后端开发概述(二).html",
    redirect: "/tech/%E5%91%A8%E8%BE%B9%E5%BC%80%E5%8F%91%E6%8A%80%E6%9C%AF/%E5%89%8D%E5%90%8E%E7%AB%AF%E5%BC%80%E5%8F%91%E6%A6%82%E8%BF%B0(%E4%BA%8C).html"
  },
  {
    name: "v-322cb124",
    path: "/tech/%E5%91%A8%E8%BE%B9%E5%BC%80%E5%8F%91%E6%8A%80%E6%9C%AF/%E5%89%8D%E5%90%8E%E7%AB%AF%E5%BC%80%E5%8F%91%E6%A6%82%E8%BF%B0.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-322cb124").then(next)
    },
  },
  {
    path: "/tech/周边开发技术/前后端开发概述.html",
    redirect: "/tech/%E5%91%A8%E8%BE%B9%E5%BC%80%E5%8F%91%E6%8A%80%E6%9C%AF/%E5%89%8D%E5%90%8E%E7%AB%AF%E5%BC%80%E5%8F%91%E6%A6%82%E8%BF%B0.html"
  },
  {
    path: "/tech/周边开发技术/前后端开发概述.html",
    redirect: "/tech/%E5%91%A8%E8%BE%B9%E5%BC%80%E5%8F%91%E6%8A%80%E6%9C%AF/%E5%89%8D%E5%90%8E%E7%AB%AF%E5%BC%80%E5%8F%91%E6%A6%82%E8%BF%B0.html"
  },
  {
    name: "v-2a9ee7be",
    path: "/tech/%E6%9C%8D%E5%8A%A1%E5%99%A8%E6%8A%80%E6%9C%AF/SpingBoot.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2a9ee7be").then(next)
    },
  },
  {
    path: "/tech/服务器技术/SpingBoot.html",
    redirect: "/tech/%E6%9C%8D%E5%8A%A1%E5%99%A8%E6%8A%80%E6%9C%AF/SpingBoot.html"
  },
  {
    path: "/tech/服务器技术/SpingBoot.html",
    redirect: "/tech/%E6%9C%8D%E5%8A%A1%E5%99%A8%E6%8A%80%E6%9C%AF/SpingBoot.html"
  },
  {
    name: "v-2081ad06",
    path: "/tech/%E6%95%B0%E6%8D%AE%E5%BA%93%E7%9B%B8%E5%85%B3/NoSql2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2081ad06").then(next)
    },
  },
  {
    path: "/tech/数据库相关/NoSql2.html",
    redirect: "/tech/%E6%95%B0%E6%8D%AE%E5%BA%93%E7%9B%B8%E5%85%B3/NoSql2.html"
  },
  {
    path: "/tech/数据库相关/NoSql2.html",
    redirect: "/tech/%E6%95%B0%E6%8D%AE%E5%BA%93%E7%9B%B8%E5%85%B3/NoSql2.html"
  },
  {
    name: "v-41b6ea0a",
    path: "/tech/%E6%95%B0%E6%8D%AE%E5%BA%93%E7%9B%B8%E5%85%B3/NoSql.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-41b6ea0a").then(next)
    },
  },
  {
    path: "/tech/数据库相关/NoSql.html",
    redirect: "/tech/%E6%95%B0%E6%8D%AE%E5%BA%93%E7%9B%B8%E5%85%B3/NoSql.html"
  },
  {
    path: "/tech/数据库相关/NoSql.html",
    redirect: "/tech/%E6%95%B0%E6%8D%AE%E5%BA%93%E7%9B%B8%E5%85%B3/NoSql.html"
  },
  {
    name: "v-100c7650",
    path: "/tech/%E6%9C%8D%E5%8A%A1%E5%99%A8%E6%8A%80%E6%9C%AF/docker.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-100c7650").then(next)
    },
  },
  {
    path: "/tech/服务器技术/docker.html",
    redirect: "/tech/%E6%9C%8D%E5%8A%A1%E5%99%A8%E6%8A%80%E6%9C%AF/docker.html"
  },
  {
    path: "/tech/服务器技术/docker.html",
    redirect: "/tech/%E6%9C%8D%E5%8A%A1%E5%99%A8%E6%8A%80%E6%9C%AF/docker.html"
  },
  {
    name: "v-75e4f2e0",
    path: "/tech/%E6%9C%8D%E5%8A%A1%E5%99%A8%E6%8A%80%E6%9C%AF/k8s.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-75e4f2e0").then(next)
    },
  },
  {
    path: "/tech/服务器技术/k8s.html",
    redirect: "/tech/%E6%9C%8D%E5%8A%A1%E5%99%A8%E6%8A%80%E6%9C%AF/k8s.html"
  },
  {
    path: "/tech/服务器技术/k8s.html",
    redirect: "/tech/%E6%9C%8D%E5%8A%A1%E5%99%A8%E6%8A%80%E6%9C%AF/k8s.html"
  },
  {
    name: "v-65986fc4",
    path: "/tech/%E6%9C%8D%E5%8A%A1%E5%99%A8%E6%8A%80%E6%9C%AF/linux.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-65986fc4").then(next)
    },
  },
  {
    path: "/tech/服务器技术/linux.html",
    redirect: "/tech/%E6%9C%8D%E5%8A%A1%E5%99%A8%E6%8A%80%E6%9C%AF/linux.html"
  },
  {
    path: "/tech/服务器技术/linux.html",
    redirect: "/tech/%E6%9C%8D%E5%8A%A1%E5%99%A8%E6%8A%80%E6%9C%AF/linux.html"
  },
  {
    name: "v-77a26158",
    path: "/tech/%E6%9C%8D%E5%8A%A1%E5%99%A8%E6%8A%80%E6%9C%AF/rust.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-77a26158").then(next)
    },
  },
  {
    path: "/tech/服务器技术/rust.html",
    redirect: "/tech/%E6%9C%8D%E5%8A%A1%E5%99%A8%E6%8A%80%E6%9C%AF/rust.html"
  },
  {
    path: "/tech/服务器技术/rust.html",
    redirect: "/tech/%E6%9C%8D%E5%8A%A1%E5%99%A8%E6%8A%80%E6%9C%AF/rust.html"
  },
  {
    name: "v-c790c146",
    path: "/tech/%E6%A1%8C%E9%9D%A2%E7%AB%AF%E5%BC%80%E5%8F%91/Electron.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c790c146").then(next)
    },
  },
  {
    path: "/tech/桌面端开发/Electron.html",
    redirect: "/tech/%E6%A1%8C%E9%9D%A2%E7%AB%AF%E5%BC%80%E5%8F%91/Electron.html"
  },
  {
    path: "/tech/桌面端开发/Electron.html",
    redirect: "/tech/%E6%A1%8C%E9%9D%A2%E7%AB%AF%E5%BC%80%E5%8F%91/Electron.html"
  },
  {
    name: "v-700df4f9",
    path: "/tech/%E6%A1%8C%E9%9D%A2%E7%AB%AF%E5%BC%80%E5%8F%91/Electron2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-700df4f9").then(next)
    },
  },
  {
    path: "/tech/桌面端开发/Electron2.html",
    redirect: "/tech/%E6%A1%8C%E9%9D%A2%E7%AB%AF%E5%BC%80%E5%8F%91/Electron2.html"
  },
  {
    path: "/tech/桌面端开发/Electron2.html",
    redirect: "/tech/%E6%A1%8C%E9%9D%A2%E7%AB%AF%E5%BC%80%E5%8F%91/Electron2.html"
  },
  {
    name: "v-4a60d5e0",
    path: "/tech/%E7%A7%BB%E5%8A%A8%E7%AB%AF/flutter.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4a60d5e0").then(next)
    },
  },
  {
    path: "/tech/移动端/flutter.html",
    redirect: "/tech/%E7%A7%BB%E5%8A%A8%E7%AB%AF/flutter.html"
  },
  {
    path: "/tech/移动端/flutter.html",
    redirect: "/tech/%E7%A7%BB%E5%8A%A8%E7%AB%AF/flutter.html"
  },
  {
    name: "v-f3b937c4",
    path: "/tech/%E7%A7%BB%E5%8A%A8%E7%AB%AF/flutter2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f3b937c4").then(next)
    },
  },
  {
    path: "/tech/移动端/flutter2.html",
    redirect: "/tech/%E7%A7%BB%E5%8A%A8%E7%AB%AF/flutter2.html"
  },
  {
    path: "/tech/移动端/flutter2.html",
    redirect: "/tech/%E7%A7%BB%E5%8A%A8%E7%AB%AF/flutter2.html"
  },
  {
    name: "v-10a350de",
    path: "/tech/%E7%A7%BB%E5%8A%A8%E7%AB%AF/flutter4.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-10a350de").then(next)
    },
  },
  {
    path: "/tech/移动端/flutter4.html",
    redirect: "/tech/%E7%A7%BB%E5%8A%A8%E7%AB%AF/flutter4.html"
  },
  {
    path: "/tech/移动端/flutter4.html",
    redirect: "/tech/%E7%A7%BB%E5%8A%A8%E7%AB%AF/flutter4.html"
  },
  {
    name: "v-69394b04",
    path: "/tech/%E7%A7%BB%E5%8A%A8%E7%AB%AF/flutter3.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-69394b04").then(next)
    },
  },
  {
    path: "/tech/移动端/flutter3.html",
    redirect: "/tech/%E7%A7%BB%E5%8A%A8%E7%AB%AF/flutter3.html"
  },
  {
    path: "/tech/移动端/flutter3.html",
    redirect: "/tech/%E7%A7%BB%E5%8A%A8%E7%AB%AF/flutter3.html"
  },
  {
    name: "v-6e9d2fbe",
    path: "/tech/%E7%A7%BB%E5%8A%A8%E7%AB%AF/h5.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6e9d2fbe").then(next)
    },
  },
  {
    path: "/tech/移动端/h5.html",
    redirect: "/tech/%E7%A7%BB%E5%8A%A8%E7%AB%AF/h5.html"
  },
  {
    path: "/tech/移动端/h5.html",
    redirect: "/tech/%E7%A7%BB%E5%8A%A8%E7%AB%AF/h5.html"
  },
  {
    name: "v-0f3281fe",
    path: "/tech/%E7%A7%BB%E5%8A%A8%E7%AB%AF/h52.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0f3281fe").then(next)
    },
  },
  {
    path: "/tech/移动端/h52.html",
    redirect: "/tech/%E7%A7%BB%E5%8A%A8%E7%AB%AF/h52.html"
  },
  {
    path: "/tech/移动端/h52.html",
    redirect: "/tech/%E7%A7%BB%E5%8A%A8%E7%AB%AF/h52.html"
  },
  {
    name: "v-5f5b75e2",
    path: "/tech/%E7%A7%BB%E5%8A%A8%E7%AB%AF/swift.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5f5b75e2").then(next)
    },
  },
  {
    path: "/tech/移动端/swift.html",
    redirect: "/tech/%E7%A7%BB%E5%8A%A8%E7%AB%AF/swift.html"
  },
  {
    path: "/tech/移动端/swift.html",
    redirect: "/tech/%E7%A7%BB%E5%8A%A8%E7%AB%AF/swift.html"
  },
  {
    name: "v-26163104",
    path: "/tech/%E7%AE%97%E6%B3%95/%E7%AE%97%E6%B3%95%E9%A2%981.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-26163104").then(next)
    },
  },
  {
    path: "/tech/算法/算法题1.html",
    redirect: "/tech/%E7%AE%97%E6%B3%95/%E7%AE%97%E6%B3%95%E9%A2%981.html"
  },
  {
    path: "/tech/算法/算法题1.html",
    redirect: "/tech/%E7%AE%97%E6%B3%95/%E7%AE%97%E6%B3%95%E9%A2%981.html"
  },
  {
    name: "v-87ed0d7c",
    path: "/tech/%E7%AE%97%E6%B3%95/%E7%AE%97%E6%B3%95%E9%A2%982.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-87ed0d7c").then(next)
    },
  },
  {
    path: "/tech/算法/算法题2.html",
    redirect: "/tech/%E7%AE%97%E6%B3%95/%E7%AE%97%E6%B3%95%E9%A2%982.html"
  },
  {
    path: "/tech/算法/算法题2.html",
    redirect: "/tech/%E7%AE%97%E6%B3%95/%E7%AE%97%E6%B3%95%E9%A2%982.html"
  },
  {
    name: "v-301fec84",
    path: "/tech/%E7%AE%97%E6%B3%95/%E7%AE%97%E6%B3%95%E9%A2%984.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-301fec84").then(next)
    },
  },
  {
    path: "/tech/算法/算法题4.html",
    redirect: "/tech/%E7%AE%97%E6%B3%95/%E7%AE%97%E6%B3%95%E9%A2%984.html"
  },
  {
    path: "/tech/算法/算法题4.html",
    redirect: "/tech/%E7%AE%97%E6%B3%95/%E7%AE%97%E6%B3%95%E9%A2%984.html"
  },
  {
    name: "v-51fcc180",
    path: "/tech/%E7%AE%97%E6%B3%95/%E7%AE%97%E6%B3%95%E9%A2%983.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-51fcc180").then(next)
    },
  },
  {
    path: "/tech/算法/算法题3.html",
    redirect: "/tech/%E7%AE%97%E6%B3%95/%E7%AE%97%E6%B3%95%E9%A2%983.html"
  },
  {
    path: "/tech/算法/算法题3.html",
    redirect: "/tech/%E7%AE%97%E6%B3%95/%E7%AE%97%E6%B3%95%E9%A2%983.html"
  },
  {
    name: "v-3ce45476",
    path: "/tech/%E9%9D%99%E6%80%81%E8%AF%AD%E8%A8%80/HTML:CSS2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3ce45476").then(next)
    },
  },
  {
    path: "/tech/静态语言/HTML:CSS2.html",
    redirect: "/tech/%E9%9D%99%E6%80%81%E8%AF%AD%E8%A8%80/HTML:CSS2.html"
  },
  {
    path: "/tech/静态语言/HTML:CSS2.html",
    redirect: "/tech/%E9%9D%99%E6%80%81%E8%AF%AD%E8%A8%80/HTML:CSS2.html"
  },
  {
    name: "v-0de264d4",
    path: "/tech/%E9%9D%99%E6%80%81%E8%AF%AD%E8%A8%80/HTML:CSS3.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0de264d4").then(next)
    },
  },
  {
    path: "/tech/静态语言/HTML:CSS3.html",
    redirect: "/tech/%E9%9D%99%E6%80%81%E8%AF%AD%E8%A8%80/HTML:CSS3.html"
  },
  {
    path: "/tech/静态语言/HTML:CSS3.html",
    redirect: "/tech/%E9%9D%99%E6%80%81%E8%AF%AD%E8%A8%80/HTML:CSS3.html"
  },
  {
    name: "v-7de351fc",
    path: "/tech/%E7%AE%97%E6%B3%95/%E7%AE%97%E6%B3%95%E9%A2%985.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7de351fc").then(next)
    },
  },
  {
    path: "/tech/算法/算法题5.html",
    redirect: "/tech/%E7%AE%97%E6%B3%95/%E7%AE%97%E6%B3%95%E9%A2%985.html"
  },
  {
    path: "/tech/算法/算法题5.html",
    redirect: "/tech/%E7%AE%97%E6%B3%95/%E7%AE%97%E6%B3%95%E9%A2%985.html"
  },
  {
    name: "v-2ca3b966",
    path: "/tech/%E9%9D%99%E6%80%81%E8%AF%AD%E8%A8%80/HTML:CSS.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2ca3b966").then(next)
    },
  },
  {
    path: "/tech/静态语言/HTML:CSS.html",
    redirect: "/tech/%E9%9D%99%E6%80%81%E8%AF%AD%E8%A8%80/HTML:CSS.html"
  },
  {
    path: "/tech/静态语言/HTML:CSS.html",
    redirect: "/tech/%E9%9D%99%E6%80%81%E8%AF%AD%E8%A8%80/HTML:CSS.html"
  },
  {
    name: "v-30e7815d",
    path: "/%E4%B8%9A%E4%BD%99%E7%A0%94%E7%A9%B6/%E5%8E%86%E5%8F%B2.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-30e7815d").then(next)
    },
  },
  {
    path: "/业余研究/历史.html",
    redirect: "/%E4%B8%9A%E4%BD%99%E7%A0%94%E7%A9%B6/%E5%8E%86%E5%8F%B2.html"
  },
  {
    path: "/业余研究/历史.html",
    redirect: "/%E4%B8%9A%E4%BD%99%E7%A0%94%E7%A9%B6/%E5%8E%86%E5%8F%B2.html"
  },
  {
    name: "v-78471c07",
    path: "/%E4%B8%9A%E4%BD%99%E7%A0%94%E7%A9%B6/%E4%BA%BA%E7%9A%84%E7%94%9F%E7%90%86%E5%AD%A6%E5%92%8C%E5%BF%83%E7%90%86%E5%AD%A6%E5%B0%8F%E7%9F%A5%E8%AF%86.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-78471c07").then(next)
    },
  },
  {
    path: "/业余研究/人的生理学和心理学小知识.html",
    redirect: "/%E4%B8%9A%E4%BD%99%E7%A0%94%E7%A9%B6/%E4%BA%BA%E7%9A%84%E7%94%9F%E7%90%86%E5%AD%A6%E5%92%8C%E5%BF%83%E7%90%86%E5%AD%A6%E5%B0%8F%E7%9F%A5%E8%AF%86.html"
  },
  {
    path: "/业余研究/人的生理学和心理学小知识.html",
    redirect: "/%E4%B8%9A%E4%BD%99%E7%A0%94%E7%A9%B6/%E4%BA%BA%E7%9A%84%E7%94%9F%E7%90%86%E5%AD%A6%E5%92%8C%E5%BF%83%E7%90%86%E5%AD%A6%E5%B0%8F%E7%9F%A5%E8%AF%86.html"
  },
  {
    name: "v-1ec6ce72",
    path: "/%E4%B8%9A%E4%BD%99%E7%A0%94%E7%A9%B6/%E6%91%84%E5%BD%B1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1ec6ce72").then(next)
    },
  },
  {
    path: "/业余研究/摄影.html",
    redirect: "/%E4%B8%9A%E4%BD%99%E7%A0%94%E7%A9%B6/%E6%91%84%E5%BD%B1.html"
  },
  {
    path: "/业余研究/摄影.html",
    redirect: "/%E4%B8%9A%E4%BD%99%E7%A0%94%E7%A9%B6/%E6%91%84%E5%BD%B1.html"
  },
  {
    name: "v-61eaf68c",
    path: "/%E4%B8%9A%E4%BD%99%E7%A0%94%E7%A9%B6/%E6%97%A5%E8%AF%AD%E5%AD%A6%E4%B9%A0%E4%B8%8E%E6%89%98%E7%A6%8F%E5%AD%A6%E4%B9%A0.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-61eaf68c").then(next)
    },
  },
  {
    path: "/业余研究/日语学习与托福学习.html",
    redirect: "/%E4%B8%9A%E4%BD%99%E7%A0%94%E7%A9%B6/%E6%97%A5%E8%AF%AD%E5%AD%A6%E4%B9%A0%E4%B8%8E%E6%89%98%E7%A6%8F%E5%AD%A6%E4%B9%A0.html"
  },
  {
    path: "/业余研究/日语学习与托福学习.html",
    redirect: "/%E4%B8%9A%E4%BD%99%E7%A0%94%E7%A9%B6/%E6%97%A5%E8%AF%AD%E5%AD%A6%E4%B9%A0%E4%B8%8E%E6%89%98%E7%A6%8F%E5%AD%A6%E4%B9%A0.html"
  },
  {
    name: "v-b67a1134",
    path: "/%E5%85%B3%E4%BA%8E/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b67a1134").then(next)
    },
  },
  {
    path: "/关于/",
    redirect: "/%E5%85%B3%E4%BA%8E/"
  },
  {
    path: "/%E5%85%B3%E4%BA%8E/index.html",
    redirect: "/%E5%85%B3%E4%BA%8E/"
  },
  {
    path: "/关于/",
    redirect: "/%E5%85%B3%E4%BA%8E/"
  },
  {
    name: "v-113b817a",
    path: "/%E5%85%B3%E4%BA%8E/about.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-113b817a").then(next)
    },
  },
  {
    path: "/关于/about.html",
    redirect: "/%E5%85%B3%E4%BA%8E/about.html"
  },
  {
    path: "/关于/about.html",
    redirect: "/%E5%85%B3%E4%BA%8E/about.html"
  },
  {
    name: "v-785538f0",
    path: "/%E7%A7%91%E5%AD%A6%E7%A0%94%E7%A9%B6/ROS.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-785538f0").then(next)
    },
  },
  {
    path: "/科学研究/ROS.html",
    redirect: "/%E7%A7%91%E5%AD%A6%E7%A0%94%E7%A9%B6/ROS.html"
  },
  {
    path: "/科学研究/ROS.html",
    redirect: "/%E7%A7%91%E5%AD%A6%E7%A0%94%E7%A9%B6/ROS.html"
  },
  {
    name: "v-72ca1346",
    path: "/%E7%A7%91%E5%AD%A6%E7%A0%94%E7%A9%B6/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-72ca1346").then(next)
    },
  },
  {
    path: "/科学研究/",
    redirect: "/%E7%A7%91%E5%AD%A6%E7%A0%94%E7%A9%B6/"
  },
  {
    path: "/%E7%A7%91%E5%AD%A6%E7%A0%94%E7%A9%B6/index.html",
    redirect: "/%E7%A7%91%E5%AD%A6%E7%A0%94%E7%A9%B6/"
  },
  {
    path: "/科学研究/",
    redirect: "/%E7%A7%91%E5%AD%A6%E7%A0%94%E7%A9%B6/"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]